export type Product = {
  id: number;
  name: string;
  slug: string;
  country: string;
  process: string;
  roast: string;
  gtin: string;
  weight: string;
  price: string;
  roastProfile: string;
  machine: string;
  image: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Brazil Santa Alina",
    slug: "brazil-santa-alina",
    country: "Brazil",
    process: "Washed",
    roast: "Light-Medium",
    gtin: "4595433537125",
    weight: "500g",
    price: "¥2,800",
    roastProfile: "Charge 180°C → Drop 213°C → DTR 3:00",
    machine: "Probat P05iii",
    image: "/images/brazil.jpg",
  },
  {
    id: 2,
    name: "Ethiopia Yirgacheffe G1",
    slug: "ethiopia-yirgacheffe-g1",
    country: "Ethiopia",
    process: "Natural",
    roast: "Light",
    gtin: "4595433537194",
    weight: "100g",
    price: "¥1,800",
    roastProfile: "FC 198–200°C → Drop 204–206°C → DTR 12%",
    machine: "Roest L100plus",
    image: "/images/ethiopia.jpg",
  },
  {
    id: 3,
    name: "Papua New Guinea Sucafina",
    slug: "papua-new-guinea-sucafina",
    country: "Papua New Guinea",
    process: "Washed",
    roast: "Medium",
    gtin: "4595433537507",
    weight: "200g",
    price: "¥2,200",
    roastProfile: "Fill 169.5°C → Drop 211.75°C → DTR ~110s",
    machine: "Probat P05iii",
    image: "/images/papua.jpg",
  },
  {
    id: 4,
    name: "Guatemala Finca Gualvador",
    slug: "guatemala-finca-gualvador",
    country: "Guatemala",
    process: "Washed",
    roast: "Medium",
    gtin: "4595433537611",
    weight: "500g",
    price: "¥3,200",
    roastProfile: "Charge 175°C → Drop 215°C → DTR 2:50",
    machine: "Probat P05iii",
    image: "/images/guatemala.jpg",
  },
  {
    id: 5,
    name: "Colombia Decaf",
    slug: "colombia-decaf",
    country: "Colombia",
    process: "Swiss Water Decaf",
    roast: "Medium",
    gtin: "4595433537728",
    weight: "400g",
    price: "¥2,600",
    roastProfile: "Charge 182°C → Drop 212°C → DTR 2:45",
    machine: "Probat P05iii",
    image: "/images/colombia-decaf.jpg",
  },
  {
    id: 6,
    name: "Panama Geisha",
    slug: "panama-geisha",
    country: "Panama",
    process: "Washed",
    roast: "Light",
    gtin: "4595433537835",
    weight: "200g",
    price: "¥4,500",
    roastProfile: "Charge 178°C → Drop 208°C → DTR 3:15",
    machine: "Roest L100plus",
    image: "/images/panama-geisha.jpg",
  },
  {
    id: 7,
    name: "Yemen White Camel",
    slug: "yemen-white-camel",
    country: "Yemen",
    process: "Natural",
    roast: "Light-Medium",
    gtin: "4595433537942",
    weight: "150g",
    price: "¥3,800",
    roastProfile: "FC 195–198°C → Drop 202–205°C → DTR 10%",
    machine: "Roest L100plus",
    image: "/images/yemen-white-camel.jpg",
  },
  {
    id: 8,
    name: "Blue Mountain No.1",
    slug: "blue-mountain-no-1",
    country: "Jamaica",
    process: "Washed",
    roast: "Medium",
    gtin: "4595433538049",
    weight: "250g",
    price: "¥4,200",
    roastProfile: "Charge 176°C → Drop 214°C → DTR 2:55",
    machine: "Probat P05iii",
    image: "/images/blue-mountain.jpg",
  },
  {
    id: 9,
    name: "El Salvador Finca La Fany",
    slug: "el-salvador-finca-la-fany",
    country: "El Salvador",
    process: "Washed",
    roast: "Medium-Dark",
    gtin: "4595433538156",
    weight: "500g",
    price: "¥3,000",
    roastProfile: "Charge 179°C → Drop 216°C → DTR 2:40",
    machine: "Probat P05iii",
    image: "/images/el-salvador.jpg",
  },
];
